# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: liberica
          java-package: jdk+fx
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew assembleDist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: markdown-writer-fx-build-artifacts
          path: |
            build/distributions
