name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]*'

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1
        if: matrix.os == 'windows-latest'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: liberica
          java-package: jdk+fx
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew jpackageImage

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: markdown-writer-fx-${{ matrix.os }}
          path: |
            build/jpackage
