name: Release

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    # necessary for uploading artifacts
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1
        if: matrix.os == 'ubuntu-latest'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: liberica
          java-package: jdk+fx
          cache: gradle

      - name: Build with Gradle
        # --no-daemon is necessary on Windows otherwise caching Gradle would fail with:
        #   tar.exe: Couldn't open ~/.gradle/caches/modules-2/modules-2.lock: Permission denied
        run: ./gradlew assembleDist --no-daemon

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith( github.ref, 'refs/tags/' )
        with:
          draft: true
          files: |
            build/distributions/*
